name: ai_chatbot
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  web_socket_channel: ^3.0.1
  http: ^1.2.1
  shared_preferences: ^2.2.2
  google_sign_in: ^6.2.1
  flutter_highlight: ^0.7.0
  flutter_markdown: ^0.7.1
  flutter_riverpod: ^2.5.1
  url_launcher: ^6.2.5
  image_picker: ^1.1.2
  file_picker: ^8.0.0+1
  path_provider: ^2.1.2
  mime: ^2.0.0
  path: ^1.9.0
  share_plus: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/aura_logo.png
    - assets/neural_core.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/aura_logo.png"
  min_sdk_android: 21
